config/routes.rb
JasmineTodoList::Application.routes.draw do
  root to: 'lists#index'

  resources :lists

  namespace :api do
    resources :lists, :defaults => { :format => 'json' }
  end
end

app/models/list.rb
class List < ActiveRecord::Base
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController
  respond_to :json
  inherit_resources

  protected
    def permitted_params
      params.permit(list: [:title, :list, :remark, :status])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :xml, :html, :json
  inherit_resources

  def create
    super do |format|
      format.html { redirect_to root_path }
    end
  end

  def update
    super do |format|
      format.html { redirect_to root_path }
    end
  end

  protected
    def permitted_params
      params.permit(list: [:title, :list, :remark, :status])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Jasmine - TODO List"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    = render '/shared/navbar'

    .container-fluid

      .row-fluid
        .span12
          = bootstrap_flash
          .row-fluid
            = yield

      %footer
        %p &copy; Jasmine Sophia Amada Ramos 2013

app/views/lists/_form.html.haml
= simple_form_for @list do |f|
  - if @list.new_record?
    = f.input :title, label: false, placeholder: 'Title'
  = f.input :list, as: :text
  = link_to "Cancel", :back, class: 'btn btn-warning'
  = f.button :submit, class: 'btn btn-primary'

app/views/lists/edit.html.haml
%h2
  = @list.title
= render 'lists/form'

app/views/lists/index.html.haml
%h2
  TODO Lists
= link_to "New", new_list_path, class: 'btn btn-primary'
%table.table.table-striped.table-hover.row-fluid
  %thead
    %tr
      %th
        Title
      %th
        List
      %th
        Remark
      %th
        Status
      %th
        Actions
  %tbody
    - @lists.each do |list|
      %tr
        %td
          = list.title
        %td
          = list.list ? simple_format(list.list.gsub('\r\n', '\n')) : "No List Yet!"
        %td
          - if list.remark.present?
            list.remark
          - else
            = "-"
        %td
          - if list.status.present?
            list.status
          - else
            = "-"
        %td#actions
          -#= link_to "Show", list_path(list), class: 'btn btn-success'
          = link_to "Edit", edit_list_path(list), class: 'btn btn-primary'
          = link_to "Delete", list_path(list), class: 'btn btn-danger', method: :delete

app/views/lists/new.html.haml
%h2
  New TODO List
= render 'lists/form'

app/views/shared/_navbar.html.haml
.navbar.navbar-fluid-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'TODO List', root_path, class: 'brand'
      -#.container.nav-collapse
        -#%ul.nav
          -#%li= link_to "Link 1", "/path1"
          -#%li= link_to "Link 2", "/path2"
          -#%li= link_to "Link 3", "/path3"